### ISSUE TITLE
Breakout Board v2.0 on Jetson Nano

### ISSUE THREAD

**Issue by drmnasr** [Myzhar/Lepton3_Jetson#1]
Hello,
Thank you for this brilliant repo, but I’ve tried connecting my breakout v2 (lepton 3.5) with the jetson nano, the link for the guide in your read me is broken but I followed the picture for connection and I connected VSYNC to pin 11.

I can detect i2c but it keeps looping “Forcing Resync”, also pylepton doesn’t just gets garbage frames. It’s worth noting that pylepton works perfectly on my RPi 4.

Am I missing something? Any ideas? Thank you

**Comment by Myzhar** [comment]
Hi @drmnasr 
I have never used the Lepton3.5 and the Breakout v2, but usually my app does a continuous "force resync" when the SPI connection does not work.
Have you tested all the SPI lines and connected the correct pins? 
For my case adding the resistor between MOSI and GND as described in my website solved many issues

**Comment by dr-m-nasr** [comment]
Hello @Myzhar 
Thank you for the reply, The link to the blog post on the website is broken actually, i couldn't find the post where you describe your connection process

**Comment by Myzhar** [comment]
Now it seems to work correctly. I think that this is the most important part for your problem:
https://www.myzhar.com/blog/jetson-nano-with-flir-lepton3/#Change_SPI_buffer_size
The default SPI buffer size on the Nano is too little to correctly handle the image data transmitted by the Lepton

**Comment by dr-m-nasr** [comment]
I believe this solved my problem, brilliant ! thank you so much !

**Comment by Myzhar** [comment]
Great :+1: 
Please close the issue if it's solved. 
Don't hesitate to contact me for any other request
