### ISSUE TITLE
Jetson clocks has to be set to on, for better performance

### ISSUE THREAD

**Issue by ma-ludw** [Myzhar/Lepton3_Jetson#14]
I noticed when I run my code with jetson clocks turned off (variable CPU frequency), the conversion to the RAW16 format sometimes takes too long. Depending on the CPU clock frequency, it takes 1ms to 5ms, or even longer (compiler set to debug, in release mode it is in between 0.5-2ms). 5ms is too long, and the next segment is read out too late and causes the communication to go out of sync and therefor you lose some frames.
If you set the jetson clocks on, the CPU stays at the max frequency and the conversion takes constantly 1ms (compiler set to debug, in release mode it is 0.5ms) and the loss of sync is less likely.

I think it would be nice if this information is added to the README.

**Comment by Myzhar** [comment]
README updated with a note in the Prerequisites. Thank you for pointing out
