### ISSUE TITLE
black video stream output in Lepton3

### ISSUE THREAD

**Issue by rahulsharma11** [Myzhar/Lepton3_Jetson#3]
Hi,
I am using Lepton3 with jetson nano with Jetpack4.3.

I was doing testing continuously with Radiomatric output. I found following results-
1) All of sudden Radiometric output video goes and complete black screen appears with no error.
2) When i switch to RGB mode then RGB video output is there with no issue. As i click "R" button to enable Radiometric output again then radiometric video out is there for 1/2 seconds and again whole thing gets black with no error.
3) When i do FFC with "f/F" button, then radiometric output video appears.

I have following doubts-
1) Is there effect of FFC in Radiometric output?
2) I am not sure with this term "Radiometric" as Lepton3 is being used not Lepton3.5
3) What if i do FFC on top every time when i start capturing Radiometric stream. Is there any problem?

Thanks.

**Comment by Myzhar** [comment]
FFC performs a calibration of the sensor. You cannot perform it for each frame... but it's good to perform it once a while.
When you switch from RGB to thermal an FFC is required to get correct thermal images.

**Comment by rahulsharma11** [comment]
Thanks
