### ISSUE TITLE
I have PureThermal mini

### ISSUE THREAD

**Issue by 11dj** [Myzhar/Lepton3_Jetson#5]
I have only PureThermal mini , FLIR Lepton 2.5 and Jetson nano 
I don't have breakout board v2 
So can I use your project 

I know how to get Thermal video from Lepton 2.5 By OpenCV (python)
but I don't know how to get temperature value 

Thanks

**Comment by Myzhar** [comment]
FLIR Lepton 2.5 has Radiometry capabilities, so you must simply enable radiometry and read the values pixel-by-pixels.
I think this is a good point to start:
https://github.com/groupgets/GetThermal

**Comment by rahulsharma11** [comment]
Hi,
That's good example to go with purethermal board and lepton3.5/2.5 sensors.

I have one more lepton3.0 and wanted to explore temp readings with purethermal board(USB interface).

Till now successfully got video and temp readings with lepton3.0 and GPIO based breakout board (Your's project) and Lepton3.5 with purethermal board.

Still no luck to get correct temp readings while using Lepton3.0 with purethermal board.
Any suggestion?
Thanks

**Comment by Myzhar** [comment]
I'm sorry, but I never used a PureThermal board. 
I used the Lepton3 only with direct SPI/I2C connection
