### ISSUE TITLE
I didn't run your project but simul_temp is manual set right?

### ISSUE THREAD

**Issue by jokerpoe** [Myzhar/Lepton3_Jetson#7]
I am a python coder guy so i didn't try to run your project!
I'm having problem with reading Lepton 3.5 temperature! It is not constant!
FFC refresh make it a little higher and the accuracy problem appeared!
I'm fiding solutions! What do you think?

**Comment by Myzhar** [comment]
Hi @jokerpoe 
unluckily I do not own a Lepton 3.5 module, but a Lepton 3 that does not provide direct temperature measure since it does not have radiometry, so I do not know its real accuracy.
What I noticed with the Lepton 3 is that after FFC it requires a few seconds to provide stable readings.

**Comment by jokerpoe** [comment]
> Hi @jokerpoe
> unluckily I do not own a Lepton 3.5 module, but a Lepton 3 that does not provide direct temperature measure since it does not have radiometry, so I do not know its real accuracy.
> What I noticed with the Lepton 3 is that after FFC it requires a few seconds to provide stable readings.

Thank you for your answer.
With me, Lepton 3.5's Temperature accuracy +- 5 deegre C is really bad experience

**Comment by Myzhar** [comment]
According to the specifications that's the expected accuracy of the Lepton3.5 module:
https://lepton.flir.com/wp-content/uploads/2015/06/Lepton3_3.5-Data-Sheet.pdf
