### ISSUE TITLE
Qt crosscompilation

### ISSUE THREAD

**Issue by Michal-Kochman** [Myzhar/Lepton3_Jetson#8]
Hi. thank you fro your work. I have followed your tutorials and tried to connect the Lepton in brekout board v2.0 to both Nvidia Jetson nano and Nvidia jetson nano 2gb dev kits, however I did not manage to establish connection. I have tried to enable spi2 on pins 13, 16, 18, 22 and 37 and tried to make the connection there, but to no effect. Could this be anything other than HW malfunction of the Lepton camera?

**Comment by Myzhar** [comment]
Jetson Nano is powerful enough to compile onboard. I never planned to cross-compile with it

**Comment by Michal-Kochman** [comment]
OK, thank you for the response. So you actually have Qt creator (or other IDE) on the Jetson, or you do not use IDE?

**Comment by Myzhar** [comment]
QtCreator without any issue. I use a SD-CARD for development
